name: Run Tests for Backend
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.URL_DB }}
      CLEAN_DATABASE_URL: ${{ secrets.URL_CLEAN_DB }}
      DEBUG: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"
      
      - name: Install dependencies
        run: pip install -r requirements.txt
        working-directory: backend
      
      - name: Run Tests
        run: pytest -v --tb=short
        working-directory: backend
      
      - name: Debug (опционально)
        if: failure()
        run: |
          echo "Current directory: $(pwd)"
          ls -la backend/ || echo "backend folder not found"
          ls -la backend/tests/ || echo "tests folder not found"