name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: TestCollector
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    
    - name: Install dependencies
      run: |
        pip install -r requirements.txt || true

    - name: Create necessary directories
      run: |
        mkdir -p app/logs
    
    - name: Run tests
      run: pytest
      env:
        TEST_URL_DB: postgresql://postgres:postgres@localhost:5432/TestCollector
        URL_DB: postgresql://postgres:postgres@localhost:5432/TestCollector
        SECRET_KEY: 62ee2c683bc919a0e1b43d8c320cf8188946b31a451312d8b4531e3fa81f667a
        ALGORITHM: HS256
        OMDB_API_KEY: 9d1e9c61
        