name: Run Tests for Backend
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    environment: testing
    env:
      DATABASE_URL: ${{ secrets.TEST_URL_DB }}
      DEBUG: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"
      
      - name: Install dependencies
        run: pip install -r app/requirements.txt
      
      - name: Run Tests
        run: pytest

      - name: Debug (опционально)
        if: failure()
        run: |
          echo "Current directory: $(pwd)"
          echo "Backend directory contents:"
          ls -la backend/ || echo "backend folder not found"